spring:
  application:
    name: HYJW_Back

  datasource:
    url: jdbc:mysql://localhost:3306/hyjwdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: your-very-long-secret-key-string-your-very-long-secret-key-at-least-32-bytes

#  web:
#    resources:
#      static-locations: file:///C:/-HaYeJiWoo-/images/
#경로 Postservice 실제 업로드 경로로 가면 ㅇㅇ : String uploadPath = "C:/typeapp/-HaYeJiWoo-/images";

#팀원마다 경로가 틀리니 수정하면서 작업하십시오. (주의)
#코하 컴퓨타 경로
uploadPath: file:///C:/typeapp/-HaYeJiWoo-/images/
itemImgLocation: C:/typeapp/-HaYeJiWoo-/images
# 지수컴퓨타 경로
#uploadPath: file:C:///-HaeYeJiWoo-/
#itemImgLocation: C:/-HaeYeJiWoo-/
#uploadPath: file:C:/-HaeYeJiWoo-/images/
#itemImgLocation: C:/-HaeYeJiWoo-/images
